// SPDX-License-Identifier: Apache-2.0

package catalog

import (
	"bytes"
	"errors"
	"fmt"
	"strings"
)

// The README's table of Twigs sits between these markers; Index rewrites it.
const (
	tableStart = "<!-- twigs:start (generated by `make index`; do not edit) -->"
	tableEnd   = "<!-- twigs:end -->"
)

// Table renders the Markdown table of every Twig.
func (c *Catalog) Table() string {
	var b strings.Builder
	b.WriteString("| Twig | Version | What it adds | Provides |\n|---|---|---|---|\n")
	for i := range c.Twigs {
		t := &c.Twigs[i]
		var provides []string
		p := t.Provides()
		for _, k := range []struct{ kind, label string }{
			{"authenticator_types", "Credential types"},
			{"hop_kinds", "Hop kinds"},
			{"tools", "Tools"},
			{"agents", "Agents"},
		} {
			if len(p[k.kind]) > 0 {
				provides = append(provides, k.label+": `"+strings.Join(p[k.kind], "`, `")+"`")
			}
		}
		if rs := t.Requires(); len(rs) > 0 {
			var names []string
			for _, r := range rs {
				names = append(names, "["+r.Name+"](twigs/"+r.Name+"/twig.yaml)")
			}
			provides = append(provides, "a bundle of "+strings.Join(names, ", "))
		}
		fmt.Fprintf(&b, "| [%s](%s) | %s | %s | %s |\n", t.Name, t.File, t.Str("version"),
			strings.ReplaceAll(t.Str("summary"), "|", "\\|"), strings.Join(provides, "; "))
	}
	return b.String()
}

// WithTable returns readme with its table of Twigs replaced.
func (c *Catalog) WithTable(readme []byte) ([]byte, error) {
	start := bytes.Index(readme, []byte(tableStart))
	end := bytes.Index(readme, []byte(tableEnd))
	if start < 0 || end < start {
		return nil, errors.New("README.md has no table markers (" + tableStart + " ... " + tableEnd + ")")
	}
	var out bytes.Buffer
	out.Write(readme[:start+len(tableStart)])
	out.WriteString("\n\n")
	out.WriteString(c.Table())
	out.WriteString("\n")
	out.Write(readme[end:])
	return out.Bytes(), nil
}
